# Generated by Django 2.2.1 on 2019-06-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190609_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbooknote',
            name='data_z',
            field=models.DateField(verbose_name='Дата занятия: *'),
        ),
        migrations.AlterField(
            model_name='classbooknote',
            name='oc',
            field=models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=20, null=True, verbose_name='Оценка:'),
        ),
        migrations.AlterField(
            model_name='classbooknote',
            name='prim',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Примечание:'),
        ),
        migrations.AlterField(
            model_name='classbooknote',
            name='pris',
            field=models.CharField(choices=[('ATTEND', 'Присутствовал'), ('ABSENT', 'Не присутствовал по неуважительной причине'), ('REASONABLE_ABSENT', 'Не присутствовал по уважительной причине'), ('WAS_ILL', 'Не присутствовал по болезни')], default='ATTEND', max_length=20, verbose_name='Присутствие: *'),
        ),
        migrations.AlterField(
            model_name='classbooknote',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Program', verbose_name='Программа: *'),
        ),
        migrations.AlterField(
            model_name='classbooknote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student', verbose_name='Ученик: *'),
        ),
        migrations.AlterField(
            model_name='classbooknote',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher', verbose_name='Учитель: *'),
        ),
        migrations.AlterField(
            model_name='classbooknote',
            name='time_z',
            field=models.TimeField(verbose_name='Время занятия: *'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='buk',
            field=models.CharField(max_length=1, verbose_name='Буква: *'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='god_z',
            field=models.IntegerField(verbose_name='Год зачисления: *'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher', verbose_name='Составитель: *'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='k_ob',
            field=models.DateField(verbose_name='Конец обучения: *'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='kol_ch',
            field=models.IntegerField(verbose_name='Количество часов: *'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='n_ob',
            field=models.DateField(verbose_name='Начало обучения: *'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='schoolyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SchoolYear', verbose_name='Учебный год: *'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject', verbose_name='Предмет: *'),
        ),
        migrations.AlterField(
            model_name='program',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher', verbose_name='Составитель: *'),
        ),
        migrations.AlterField(
            model_name='program',
            name='kol_ch',
            field=models.IntegerField(verbose_name='Количество часов: *'),
        ),
        migrations.AlterField(
            model_name='program',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Plan', verbose_name='План: *'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tema',
            field=models.CharField(max_length=30, verbose_name='Тема урока: *'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Klass', verbose_name='Класс: *'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='kon_g',
            field=models.DateField(verbose_name='Конец года: *'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='nach_g',
            field=models.DateField(verbose_name='Начало года: *'),
        ),
        migrations.AlterField(
            model_name='student',
            name='data_r',
            field=models.DateField(verbose_name='Дата рождения: *'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fio_uch',
            field=models.CharField(max_length=50, verbose_name='ФИО ученика: *'),
        ),
        migrations.AlterField(
            model_name='student',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Klass', verbose_name='Класс: *'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pred',
            field=models.CharField(max_length=30, verbose_name='Предмет: *'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher', verbose_name='Учитель: *'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dol',
            field=models.CharField(choices=[('TEACHER', 'Учитель'), ('VICE_PRINCIPAL', 'Завуч')], max_length=50, verbose_name='Должность: *'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fio_uchit',
            field=models.CharField(max_length=50, verbose_name='ФИО учителя: *'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='log',
            field=models.CharField(max_length=50, verbose_name='Логин: *'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mail',
            field=models.CharField(max_length=50, verbose_name='E-mail: *'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='par',
            field=models.CharField(max_length=50, verbose_name='Пароль: *'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tel',
            field=models.CharField(max_length=50, verbose_name='Телефон: *'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tip',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('USER', 'Пользователь')], max_length=50, verbose_name='Тип пользователя: *'),
        ),
    ]
