# Generated by Django 2.2.1 on 2019-06-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190609_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teacher', verbose_name='Учитель: *'),
        ),
    ]
