# Generated by Django 2.2.1 on 2019-06-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190610_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbooknote',
            name='prim',
            field=models.CharField(blank=True, choices=[('1', '1 четверть'), ('2', '2 четверть'), ('3', '3 четверть'), ('4', '4 четверть'), ('YEAR', 'Год')], max_length=5, null=True, verbose_name='Примечание:'),
        ),
    ]
